### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by mikebronner** [bluekeyes/Fusion360-ExportCutlist#21] opened 2024-02-14 01:19 UTC
received the following stack trace when trying to export to Cutlist Evo format:

```
Failed:
Traceback (most recent call last):
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 44, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 281, in notify
    cutlist.add(selectionInput.selection(i).entity)
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 151, in add
    self.add(child, self._joinname(name, obj.component.name))
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 151, in add
    self.add(child, self._joinname(name, obj.component.name))
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 149, in add
    self.add_body(body, self._joinname(name, obj.component.name, body.name))
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 128, in add_body
    minimal_body = get_minimal_body(body)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/lib/geometry/bodies.py", line 45, in get_minimal_body
    transform.setToAlignCoordinateSystems(origin, orientation, cross_orientation, normal, origin, target_x, target_y, target_z)
  File "/Users/mike/Library/Application Support/Autodesk/webdeploy/production/d1fe173da69e6a3d046df6e4dd1bd5a29091fcf5/Autodesk Fusion 360.app/Contents/Api/Python/packages/adsk/core.py", line 13030, in setToAlignCoordinateSystems
    return _core.Matrix3D_setToAlignCoordinateSystems(self, fromOrigin, fromXAxis, fromYAxis, fromZAxis, toOrigin, toXAxis, toYAxis, toZAxis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 3 : invalid argument fromXAxis
```

I got the same or similar error when trying to export to Cutlist Optimizer format:
```
Failed:
Traceback (most recent call last):
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 44, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 281, in notify
    cutlist.add(selectionInput.selection(i).entity)
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 151, in add
    self.add(child, self._joinname(name, obj.component.name))
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 151, in add
    self.add(child, self._joinname(name, obj.component.name))
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 149, in add
    self.add_body(body, self._joinname(name, obj.component.name, body.name))
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/ExportCutlist.py", line 128, in add_body
    minimal_body = get_minimal_body(body)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/Downloads/Fusion360-ExportCutlist-0.5.1/lib/geometry/bodies.py", line 45, in get_minimal_body
    transform.setToAlignCoordinateSystems(origin, orientation, cross_orientation, normal, origin, target_x, target_y, target_z)
  File "/Users/mike/Library/Application Support/Autodesk/webdeploy/production/d1fe173da69e6a3d046df6e4dd1bd5a29091fcf5/Autodesk Fusion 360.app/Contents/Api/Python/packages/adsk/core.py", line 13030, in setToAlignCoordinateSystems
    return _core.Matrix3D_setToAlignCoordinateSystems(self, fromOrigin, fromXAxis, fromYAxis, fromZAxis, toOrigin, toXAxis, toYAxis, toZAxis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 3 : invalid argument fromXAxis
```

Fusion version: Fusion 2.0.18441 arm64 [Native] 
macOS 14.3.1 (23D60)
M1 Mac Studio

**Comment by bluekeyes** [comment] 2024-02-14 05:51
Thanks for reporting this! I think it should be fixed in [0.5.2](https://github.com/bluekeyes/Fusion360-ExportCutlist/releases/tag/v0.5.2).

It looks like your design is hitting an uncommon branch that had an uninitialized variable, which means you may see other errors or unexpected behavior. If you do, I'd appreciate if you could share a design file that demonstrates the issue - it makes debugging and testing much easier.

**Closed as completed by bluekeyes** 2024-02-14 05:51 UTC
